from __future__ import annotations

from mpf.domain.production import ManualCanaryAcceptanceRequest


REQUIREMENT_FIELDS = (
    "require_farm5_phase11c_evidence",
    "require_backup_reference",
    "require_restore_plan_reference",
    "require_rollback_plan",
    "require_no_customer_nat_baseline",
    "require_no_customer_firewall_baseline",
    "require_local_only_runtime_baseline",
)


def build_phase11_manual_canary_acceptance_report(request: ManualCanaryAcceptanceRequest) -> dict[str, object]:
    validation_errors = request.validate()
    missing_requirement_blocked = any(not getattr(request, field) for field in REQUIREMENT_FIELDS)
    if missing_requirement_blocked:
        validation_errors.append("all requirement toggles must remain enabled for Phase 11D package")

    ready = not validation_errors and request.requested_action == "package"
    final_decision = "MANUAL_CANARY_PACKAGE_READY_FOR_FARM5_SYNC_EVIDENCE" if ready else "BLOCKED"

    return {
        "component": "phase11_manual_canary_acceptance",
        "phase": "Phase 11D — Manual canary customer acceptance package",
        "final_decision": final_decision,
        "authorization_status": "MANUAL_CANARY_PACKAGE_NON_AUTHORIZING",
        "execution_allowed": False,
        "report_only": False,
        "acceptance_package_mode": True,
        "mutation_performed": False,
        "live_canary_performed": False,
        "customer_db_mutation_performed": False,
        "firewall_mutation_performed": False,
        "nat_mutation_performed": False,
        "conntrack_mutation_performed": False,
        "production_traffic_enabled": False,
        "request": request.as_dict(),
        "gate": {
            "phase11a_farm5_evidence_recorded": True,
            "phase11b_farm5_evidence_recorded": True,
            "phase11c_farm5_evidence_recorded": True,
            "phase11d_package_farm5_evidence_required_after_merge": True,
            "phase11d_execution_authorized": False,
            "phase11_final_acceptance_required_later": True,
            "production_activation_requires_final_phase11_acceptance": True,
        },
        "required_pre_execution_evidence": {
            "mpf_version_required": True,
            "phase_status_required": True,
            "mpf_doctor_required": True,
            "db_status_required": True,
            "proxy_doctor_required": True,
            "production_readiness_required": True,
            "canary_plan_required": True,
            "activation_harness_required": True,
            "phase_gate_required": True,
            "no_customer_nat_baseline_required": True,
            "no_customer_firewall_baseline_required": True,
            "local_only_listener_baseline_required": True,
            "backup_reference_required": True,
            "restore_plan_reference_required": True,
            "rollback_plan_required": True,
            "operator_confirmation_required": True,
        },
        "future_manual_canary_steps_preview": {
            "would_create_or_select_canary_customer": True,
            "would_prepare_customer_db_mutation_under_later_gate": True,
            "would_prepare_firewall_apply_under_later_gate": True,
            "would_prepare_customer_nat_under_later_gate": True,
            "would_prepare_customer_firewall_rules_under_later_gate": True,
            "would_verify_backend_connectivity_under_later_gate": True,
            "would_verify_usage_visibility_under_later_gate": True,
            "would_verify_reject_visibility_under_later_gate": True,
            "would_verify_abuse_1h_coverage_under_later_gate": True,
            "would_collect_canary_success_evidence_under_later_gate": True,
            "would_require_rollback_or_restore_plan_under_later_gate": True,
        },
        "acceptance_criteria": [
            "server source aligned with GitHub main",
            "phase gate still Phase 10 accepted / Phase 11 planning-readiness before future execution",
            "apply mode remains plan_only until later explicit execution gate",
            "no MPF/customer NAT redirects before future execution",
            "no MPF/customer firewall rules before future execution",
            "accepted listeners remain local-only before future execution",
            "manual canary customer intent reviewed",
            "backup/restore/rollback plan reviewed",
            "operator explicitly confirms before any future execution",
            "future evidence must prove customer traffic path, usage visibility, reject visibility, and rollback readiness",
            "abuse 1h coverage must remain required before limited onboarding",
        ],
        "execution_boundary": {
            "accept_command_surface_present": True,
            "accept_execution_allowed_in_this_pr": False,
            "execute_execution_allowed_in_this_pr": False,
            "requested_accept_blocked": request.requested_action == "accept",
            "requested_execute_blocked": request.requested_action == "execute",
            "operator_confirmation_required": True,
            "operator_confirmation_disabled_blocked": not request.require_operator_confirmation,
            "missing_requirement_blocked": missing_requirement_blocked,
            "future_phase_required_for_execution": "Later explicit Phase 11D execution gate after farm5 package evidence",
        },
        "safety_flags": {
            "production_traffic_authorized": False,
            "controlled_cli_canary_execution_authorized": False,
            "limited_customer_onboarding_authorized": False,
            "customer_db_mutation_authorized": False,
            "firewall_apply_authorized": False,
            "iptables_restore_authorized": False,
            "customer_nat_apply_authorized": False,
            "customer_firewall_rules_apply_authorized": False,
            "abuse_automation_authorized": False,
            "conntrack_flush_authorized": False,
            "worker_enforcement_authorized": False,
            "scheduler_authorized": False,
            "collector_authorized": False,
            "ui_authorized": False,
            "telegram_authorized": False,
        },
        "operator_checklist": [
            "sync latest GitHub main to farm5 after merge",
            "run mpf --version",
            "run mpf phase-status",
            "run mpf config validate",
            "run mpf doctor",
            "run mpf db status",
            "run mpf proxy doctor",
            "run mpf production readiness --output json",
            "run mpf production canary-plan --output json",
            "run mpf production activation-harness --output json",
            "run mpf production canary-acceptance --output json",
            "run bash scripts/verify_current_phase_gate.sh",
            "verify no MPF/customer NAT redirects",
            "verify no MPF/customer firewall rules",
            "do not connect real miner in this PR",
            "do not execute accept/execute in this PR",
            "collect farm5 package evidence before any later execution gate",
        ],
        "blockers": [
            "farm5 Phase 11D package sync/test evidence required after merge",
            "actual manual canary execution remains forbidden until explicit later gate",
            "requested accept/execute remains blocked in this PR",
            "firewall apply remains forbidden in this PR",
            "customer NAT/customer firewall rules remain preview-only",
            "customer DB mutation remains forbidden in this PR",
            "production traffic remains none",
            "abuse automation remains forbidden",
            "limited real customer onboarding remains forbidden",
        ],
        "validation_errors": validation_errors,
        "next_required_step": "Merge PR, sync main to farm5, run Phase 11A/11B/11C/11D package evidence commands, then record farm5 evidence before any later manual canary execution gate.",
    }
