from __future__ import annotations

from mpf.domain.production import ControlledActivationHarnessRequest


def build_phase11_controlled_activation_harness_report(request: ControlledActivationHarnessRequest) -> dict[str, object]:
    validation_errors = request.validate()
    preflight_or_package = request.requested_action in {"preflight", "package"}
    ready = not validation_errors and preflight_or_package and request.dry_run

    final_decision = "HARNESS_READY_FOR_FARM5_SYNC_EVIDENCE" if ready else "BLOCKED"

    return {
        "component": "phase11_controlled_activation_harness",
        "phase": "Phase 11C — Controlled activation harness",
        "final_decision": final_decision,
        "authorization_status": "CONTROLLED_HARNESS_NON_AUTHORIZING",
        "execution_allowed": False,
        "report_only": False,
        "harness_mode": True,
        "mutation_performed": False,
        "live_apply_performed": False,
        "customer_db_mutation_performed": False,
        "firewall_mutation_performed": False,
        "nat_mutation_performed": False,
        "conntrack_mutation_performed": False,
        "request": {
            "customer_key": request.customer_key,
            "lane": request.lane,
            "port": request.port,
            "name": request.name,
            "miners": request.miners,
            "farms": request.farms,
            "maxconn": request.maxconn,
            "rate_per_min": request.rate_per_min,
            "burst": request.burst,
            "ips_mode": request.ips_mode,
            "ip_whitelist": request.ip_whitelist,
            "operator": request.operator,
            "reason": request.reason,
            "requested_action": request.requested_action,
            "dry_run": request.dry_run,
            "require_operator_confirmation": request.require_operator_confirmation,
        },
        "gate": {
            "phase11a_farm5_evidence_recorded": True,
            "phase11b_farm5_evidence_recorded": True,
            "phase11c_farm5_evidence_required_after_merge": True,
            "phase11c_execution_authorized": False,
            "phase11d_manual_canary_required_later": True,
            "production_activation_requires_final_phase11_acceptance": True,
        },
        "preflight_checks": {
            "phase10_accepted": True,
            "phase11_working": True,
            "phase11a_evidence_recorded": True,
            "phase11b_evidence_recorded": True,
            "apply_mode_must_remain_plan_only": True,
            "no_customer_nat_redirects_required": True,
            "no_customer_firewall_rules_required": True,
            "local_only_runtime_required": True,
            "backup_required_before_future_apply": True,
            "restore_point_required_before_future_apply": True,
            "lock_required_before_future_apply": True,
            "verify_required_after_future_apply": True,
            "rollback_plan_required": True,
            "operator_confirmation_required": True,
            "abuse_1h_coverage_required_before_limited_onboarding": True,
        },
        "activation_package": {
            "would_validate_customer_intent": True,
            "would_prepare_customer_db_mutation_plan": True,
            "would_prepare_firewall_desired_model": True,
            "would_prepare_customer_nat_preview": True,
            "would_prepare_customer_firewall_rules_preview": True,
            "would_prepare_usage_reject_visibility_checks": True,
            "would_prepare_abuse_1h_coverage_checks": True,
            "would_prepare_backup_reference": True,
            "would_prepare_restore_plan_reference": True,
            "would_prepare_lock_id": True,
            "would_prepare_verify_plan": True,
            "would_prepare_rollback_plan": True,
        },
        "execution_boundary": {
            "apply_command_surface_present": True,
            "apply_execution_allowed_in_this_pr": False,
            "dry_run_required": True,
            "no_dry_run_blocked": not request.dry_run,
            "requested_apply_blocked": request.requested_action == "apply",
            "future_phase_required_for_apply": "Phase 11D manual canary / accepted controlled gate after farm5 evidence",
        },
        "safety_flags": {
            "production_traffic_authorized": False,
            "controlled_cli_canary_execution_authorized": False,
            "limited_customer_onboarding_authorized": False,
            "customer_db_mutation_authorized": False,
            "firewall_apply_authorized": False,
            "iptables_restore_authorized": False,
            "customer_nat_apply_authorized": False,
            "customer_firewall_rules_apply_authorized": False,
            "abuse_automation_authorized": False,
            "conntrack_flush_authorized": False,
            "worker_enforcement_authorized": False,
            "scheduler_authorized": False,
            "collector_authorized": False,
            "ui_authorized": False,
            "telegram_authorized": False,
        },
        "operator_checklist": [
            "sync latest GitHub main to farm5 after merge",
            "run mpf production readiness --output json",
            "run mpf production canary-plan --output json",
            "run mpf production activation-harness --output json",
            "verify mpf doctor",
            "verify mpf db status",
            "verify mpf proxy doctor",
            "verify current phase gate",
            "verify no MPF/customer NAT redirects",
            "verify no MPF/customer firewall rules",
            "do not execute apply in Phase 11C",
            "do not connect real miner in Phase 11C",
            "collect evidence before Phase 11D",
        ],
        "blockers": [
            "farm5 Phase 11C sync/test evidence required after merge",
            "actual canary execution remains forbidden until explicit later gate",
            "firewall apply remains forbidden in this PR",
            "customer NAT/customer firewall rules remain preview-only",
            "customer DB mutation remains forbidden in this PR",
            "production traffic remains none",
            "abuse automation remains forbidden",
        ],
        "validation_errors": validation_errors,
        "next_required_step": "Merge PR, sync main to farm5, run Phase 11A/11B/11C evidence commands, then record farm5 evidence before any Phase 11D manual canary execution.",
    }
