from __future__ import annotations
import json
from pathlib import Path
from types import SimpleNamespace
from typer.testing import CliRunner
from mpf.config import load_config
from mpf.interfaces.cli import app
from mpf.services import customer_read_service
from mpf.services.phase11_single_customer_post_apply_evidence_service import build_phase11_single_customer_post_apply_evidence_report


def _cfg(): return load_config(Path('configs/mpf.example.yaml'))
def _rows(*r): return customer_read_service.CustomerList(ok=True,message='ok',customers=list(r))
def _staged(status='paused',lane='btc',port=20101,key='limited-btc-001'): return SimpleNamespace(customer_key=key,lane=lane,port=port,status=status)
def _pre(): return '*nat\n:MPF_NAT_PRE - [0:0]\n-A MPF_NAT_PRE -p tcp -m comment --comment "mpf:canary-btc-001:customer_nat_redirect" --dport 20001 -j DNAT --to-destination 172.18.0.3:60010\n*filter\n:MPFC_20001 - [0:0]\n'
def _post(extra=''): return _pre()+':MPFC_20101 - [0:0]\n-A MPF_NAT_PRE -p tcp -m comment --comment "mpf:limited-btc-001:customer_nat_redirect" --dport 20101 -j DNAT --to-destination 172.18.0.3:60010\n-A MPFC_20101 -p tcp --dport 20101 -m comment --comment "mpf:limited-btc-001:customer_connlimit_reject" -j REJECT\n-A MPFC_20101 -p tcp --dport 20101 -m comment --comment "mpf:limited-btc-001:customer_hashlimit_reject" -j REJECT\n'+extra
def _write(tmp,n,t): p=tmp/n; p.write_text(t); return p

def _exec(**u):
    d={"final_decision":"PHASE11_SINGLE_CUSTOMER_FIREWALL_APPLY_EXECUTED_PENDING_REVIEW","execute_requested":True,"apply_execution_ready":True,"firewall_apply_execution_allowed":True,"iptables_restore_authorized":True,"mutation_performed":True,"firewall_mutation_performed":True,"nat_mutation_performed":True,"blockers":[],"warnings":[],"next_required_step":"phase11e_post_apply_runtime_evidence_pr","candidate_customer_key":"limited-btc-001","candidate_lane":"btc","candidate_public_port":20101,"candidate_backend_target":"172.18.0.3:60010","production_traffic_enabled":False,"miner_traffic_allowed":False,"phase11_accepted":False,"post_apply_verification":{"mpf_nat_pre_exists":True,"mpfc_20001_exists":True,"mpfc_20101_exists":True,"canary_20001_exact_artifact_preserved":True,"dnat_20101_exact_target_count":1,"dnat_20101_loopback_count":0,"unrelated_customer_nat_rule_count":0,"limited_20101_connlimit_reject_rule_count":1,"limited_20101_hashlimit_reject_rule_count":1,"limited_20101_filter_primitives_verified":True}}
    d.update(u); return d

def _kw(tmp,**u):
    d=dict(execution_json=_write(tmp,'e.json',json.dumps(_exec())),execution_json_sha256='bd8f3900db3d3fb2647ead8cec47c870f4cd00ebaf52b68bc329a065a65b880b',pre_apply_snapshot_file=_write(tmp,'pre.txt',_pre()),pre_apply_snapshot_sha256='3a493643f796f10f37443152e99adda928f30c82067fc98a4a748f52d2767494',post_apply_snapshot_file=_write(tmp,'post.txt',_post()),post_apply_snapshot_sha256='c6330a80954f7268ccec311750751b45464c84c2efd627509d1ecee274eec27b',apply_gate_json=_write(tmp,'a.json','x'),apply_gate_json_sha256='2d711642b726b04401627ca9fbac32f5da7e5d0f1b2c9d7f3d5b4a6c8e1f0a2',plan_gate_json=_write(tmp,'p.json','y'),plan_gate_json_sha256='a1fce4363854ff888cff4b8e7875d600c268239041f7af2bbfc4618cbafe0f8d',operator='vahid',reason='ok',operator_confirmed=True,i_understand_post_apply_evidence_only=True,i_understand_no_additional_firewall_apply=True,i_understand_no_production_traffic_acceptance=True,i_understand_no_miner_traffic_acceptance=True,i_confirm_runtime_path_evidence_required_next=True,i_confirm_stratum_transcript_required_next=True,i_confirm_visibility_bundle_required_next=True,i_confirm_abuse_1h_required_before_customer_traffic=True,i_confirm_restart_container_order_required_before_limited_acceptance=True)
    import hashlib
    d['pre_apply_snapshot_sha256']=hashlib.sha256(Path(d['pre_apply_snapshot_file']).read_bytes()).hexdigest()
    d['post_apply_snapshot_sha256']=hashlib.sha256(Path(d['post_apply_snapshot_file']).read_bytes()).hexdigest()
    d['execution_json_sha256']=hashlib.sha256(Path(d['execution_json']).read_bytes()).hexdigest()
    d['apply_gate_json_sha256']=hashlib.sha256(Path(d['apply_gate_json']).read_bytes()).hexdigest()
    d['plan_gate_json_sha256']=hashlib.sha256(Path(d['plan_gate_json']).read_bytes()).hexdigest()
    d.update(u); return d

def _run(tmp,mp,**u): mp.setattr(customer_read_service,'list_customer_status',lambda *a,**k:_rows(_staged())); return build_phase11_single_customer_post_apply_evidence_report(_cfg(),**_kw(tmp,**u))

def test_01_ready(tmp_path,monkeypatch): assert _run(tmp_path,monkeypatch)['final_decision']=='PHASE11_SINGLE_CUSTOMER_POST_APPLY_EVIDENCE_READY'
def test_02_missing_exec(tmp_path,monkeypatch): assert 'execution_json_missing' in _run(tmp_path,monkeypatch,execution_json=tmp_path/'x')['blockers']
def test_03_invalid_exec(tmp_path,monkeypatch): p=_write(tmp_path,'bad.json','{'); assert 'execution_json_invalid' in _run(tmp_path,monkeypatch,execution_json=p)['blockers']
def test_04_exec_hash_mismatch(tmp_path,monkeypatch): assert 'execution_json_hash_mismatch' in _run(tmp_path,monkeypatch,execution_json_sha256='x')['blockers']
def test_05_exec_not_success(tmp_path,monkeypatch): p=_write(tmp_path,'e2.json',json.dumps(_exec(final_decision='X'))); assert 'execution_json_not_success' in _run(tmp_path,monkeypatch,execution_json=p)['blockers']
def test_06_scope_mismatch(tmp_path,monkeypatch): p=_write(tmp_path,'e3.json',json.dumps(_exec(candidate_lane='zec'))); assert 'execution_json_scope_mismatch' in _run(tmp_path,monkeypatch,execution_json=p)['blockers']
def test_07_safety_open(tmp_path,monkeypatch): p=_write(tmp_path,'e4.json',json.dumps(_exec(blockers=['x']))); assert 'execution_json_safety_boundary_open' in _run(tmp_path,monkeypatch,execution_json=p)['blockers']
def test_08_missing_post_apply_verification(tmp_path,monkeypatch): p=_write(tmp_path,'e5.json',json.dumps(_exec(post_apply_verification=None))); assert 'execution_json_post_apply_verification_missing' in _run(tmp_path,monkeypatch,execution_json=p)['blockers']
def test_09_failed_post_apply_verification(tmp_path,monkeypatch): p=_write(tmp_path,'e6.json',json.dumps(_exec(post_apply_verification={}))); assert 'execution_json_post_apply_verification_failed' in _run(tmp_path,monkeypatch,execution_json=p)['blockers']
def test_10_pre_hash_mismatch(tmp_path,monkeypatch): assert 'pre_apply_snapshot_hash_mismatch' in _run(tmp_path,monkeypatch,pre_apply_snapshot_sha256='x')['blockers']
def test_11_post_hash_mismatch(tmp_path,monkeypatch): assert 'post_apply_snapshot_hash_mismatch' in _run(tmp_path,monkeypatch,post_apply_snapshot_sha256='x')['blockers']
def test_12_pre_has_20101(tmp_path,monkeypatch): assert 'pre_apply_snapshot_unexpected_20101_present' in _run(tmp_path,monkeypatch,pre_apply_snapshot_file=_write(tmp_path,'pre2.txt',_post()))['blockers']
def test_13_post_missing_20101(tmp_path,monkeypatch): assert 'post_apply_snapshot_missing_20101' in _run(tmp_path,monkeypatch,post_apply_snapshot_file=_write(tmp_path,'post2.txt',_pre()))['blockers']
def test_14_post_missing_canary(tmp_path,monkeypatch): assert 'post_apply_snapshot_missing_canary_20001' in _run(tmp_path,monkeypatch,post_apply_snapshot_file=_write(tmp_path,'post3.txt',':MPFC_20101\n'))['blockers']
def test_15_post_duplicate_20101(tmp_path,monkeypatch): assert 'post_apply_snapshot_duplicate_20101' in _run(tmp_path,monkeypatch,post_apply_snapshot_file=_write(tmp_path,'post4.txt',_post('\n-A MPF_NAT_PRE -p tcp -m comment --comment "mpf:limited-btc-001:customer_nat_redirect" --dport 20101 -j DNAT --to-destination 172.18.0.3:60010')) )['blockers']
def test_16_post_loopback_20101(tmp_path,monkeypatch): assert 'post_apply_snapshot_loopback_20101' in _run(tmp_path,monkeypatch,post_apply_snapshot_file=_write(tmp_path,'post5.txt',_post('\n-A MPF_NAT_PRE -p tcp --dport 20101 -j DNAT --to-destination 127.0.0.1:60010')) )['blockers']
def test_17_unrelated_nat(tmp_path,monkeypatch): assert 'post_apply_snapshot_unrelated_customer_nat' in _run(tmp_path,monkeypatch,post_apply_snapshot_file=_write(tmp_path,'post6.txt',_post('\n-A MPF_NAT_PRE -p tcp -m comment --comment "mpf:other:customer_nat_redirect" --dport 30000 -j DNAT --to-destination 1.1.1.1:1')) )['blockers']
def test_18_db_fail(tmp_path,monkeypatch): monkeypatch.setattr(customer_read_service,'list_customer_status',lambda *a,**k: customer_read_service.CustomerList(ok=False,message='x',customers=[])); assert 'db_read_failed' in build_phase11_single_customer_post_apply_evidence_report(_cfg(),**_kw(tmp_path))['blockers']
def test_19_missing_customer(tmp_path,monkeypatch): monkeypatch.setattr(customer_read_service,'list_customer_status',lambda *a,**k:_rows()); assert 'staged_customer_missing' in build_phase11_single_customer_post_apply_evidence_report(_cfg(),**_kw(tmp_path))['blockers']
def test_20_duplicate_customer(tmp_path,monkeypatch): monkeypatch.setattr(customer_read_service,'list_customer_status',lambda *a,**k:_rows(_staged(),_staged())); assert 'staged_customer_duplicate' in build_phase11_single_customer_post_apply_evidence_report(_cfg(),**_kw(tmp_path))['blockers']
def test_21_wrong_lane_port(tmp_path,monkeypatch): monkeypatch.setattr(customer_read_service,'list_customer_status',lambda *a,**k:_rows(_staged(lane='zec'))); assert 'staged_customer_scope_mismatch' in build_phase11_single_customer_post_apply_evidence_report(_cfg(),**_kw(tmp_path))['blockers']
def test_22_not_paused(tmp_path,monkeypatch): monkeypatch.setattr(customer_read_service,'list_customer_status',lambda *a,**k:_rows(_staged(status='active'))); assert 'staged_customer_not_paused' in build_phase11_single_customer_post_apply_evidence_report(_cfg(),**_kw(tmp_path))['blockers']
def test_23_port_collision(tmp_path,monkeypatch): monkeypatch.setattr(customer_read_service,'list_customer_status',lambda *a,**k:_rows(_staged(),_staged(key='x'))); assert 'candidate_port_collision' in build_phase11_single_customer_post_apply_evidence_report(_cfg(),**_kw(tmp_path))['blockers']
def test_24_missing_operator(tmp_path,monkeypatch): assert 'operator_not_confirmed' in _run(tmp_path,monkeypatch,operator_confirmed=False)['blockers']
def test_25_missing_evidence_only_confirm(tmp_path,monkeypatch): assert 'post_apply_evidence_only_not_confirmed' in _run(tmp_path,monkeypatch,i_understand_post_apply_evidence_only=False)['blockers']
def test_26_missing_no_additional_apply_confirm(tmp_path,monkeypatch): assert 'no_additional_firewall_apply_not_confirmed' in _run(tmp_path,monkeypatch,i_understand_no_additional_firewall_apply=False)['blockers']
def test_27_missing_remaining_confirms(tmp_path,monkeypatch): r=_run(tmp_path,monkeypatch,i_confirm_runtime_path_evidence_required_next=False,i_confirm_stratum_transcript_required_next=False,i_confirm_visibility_bundle_required_next=False,i_confirm_abuse_1h_required_before_customer_traffic=False,i_confirm_restart_container_order_required_before_limited_acceptance=False); assert 'runtime_path_required_not_confirmed' in r['blockers']
def test_28_live_snapshot_match(tmp_path,monkeypatch): p=_write(tmp_path,'live.txt',_post()); assert _run(tmp_path,monkeypatch,live_snapshot_file=p)['final_decision']=='PHASE11_SINGLE_CUSTOMER_POST_APPLY_EVIDENCE_READY'
def test_29_live_mismatch_blocks(tmp_path,monkeypatch): p=_write(tmp_path,'live2.txt',_pre()); assert 'post_apply_snapshot_missing_20101' in _run(tmp_path,monkeypatch,live_snapshot_file=p)['blockers']
def test_30_output_never_authorizes(tmp_path,monkeypatch): r=_run(tmp_path,monkeypatch); assert r['production_traffic_enabled'] is False and r['miner_traffic_allowed'] is False and r['phase11_accepted'] is False and r['additional_firewall_apply_allowed'] is False

def test_31_cli_json(tmp_path,monkeypatch):
    monkeypatch.setattr(customer_read_service,'list_customer_status',lambda *a,**k:_rows(_staged()));
    e=_write(tmp_path,'e.json',json.dumps(_exec())); pre=_write(tmp_path,'pre.txt',_pre()); post=_write(tmp_path,'post.txt',_post()); a=_write(tmp_path,'a.json','x'); p=_write(tmp_path,'p.json','y')
    r=CliRunner().invoke(app,['production','single-customer-post-apply-evidence','--execution-json',str(e),'--execution-json-sha256','bd8f3900db3d3fb2647ead8cec47c870f4cd00ebaf52b68bc329a065a65b880b','--pre-apply-snapshot-file',str(pre),'--pre-apply-snapshot-sha256','3a493643f796f10f37443152e99adda928f30c82067fc98a4a748f52d2767494','--post-apply-snapshot-file',str(post),'--post-apply-snapshot-sha256','c6330a80954f7268ccec311750751b45464c84c2efd627509d1ecee274eec27b','--apply-gate-json',str(a),'--apply-gate-json-sha256','2d711642b726b04401627ca9fbac32f5da7e5f3c6f2f7f8f2f8f90fdbf1f5e2f','--plan-gate-json',str(p),'--plan-gate-json-sha256','a1fce4363854ff888cff4b8e7875d600c268239041f7af2bbfc4618cbafe0f8d','--operator','vahid','--reason','ok','--operator-confirmed','--i-understand-post-apply-evidence-only','--i-understand-no-additional-firewall-apply','--i-understand-no-production-traffic-acceptance','--i-understand-no-miner-traffic-acceptance','--i-confirm-runtime-path-evidence-required-next','--i-confirm-stratum-transcript-required-next','--i-confirm-visibility-bundle-required-next','--i-confirm-abuse-1h-required-before-customer-traffic','--i-confirm-restart-container-order-required-before-limited-acceptance','--output','json','--config','configs/mpf.example.yaml']); assert r.exit_code==0

def test_32_cli_human(tmp_path,monkeypatch):
    monkeypatch.setattr(customer_read_service,'list_customer_status',lambda *a,**k:_rows(_staged()));
    e=_write(tmp_path,'e2.json',json.dumps(_exec())); pre=_write(tmp_path,'pre2.txt',_pre()); post=_write(tmp_path,'post2.txt',_post()); a=_write(tmp_path,'a2.json','x'); p=_write(tmp_path,'p2.json','y')
    r=CliRunner().invoke(app,['production','single-customer-post-apply-evidence','--execution-json',str(e),'--execution-json-sha256','bd8f3900db3d3fb2647ead8cec47c870f4cd00ebaf52b68bc329a065a65b880b','--pre-apply-snapshot-file',str(pre),'--pre-apply-snapshot-sha256','3a493643f796f10f37443152e99adda928f30c82067fc98a4a748f52d2767494','--post-apply-snapshot-file',str(post),'--post-apply-snapshot-sha256','c6330a80954f7268ccec311750751b45464c84c2efd627509d1ecee274eec27b','--apply-gate-json',str(a),'--apply-gate-json-sha256','2d711642b726b04401627ca9fbac32f5da7e5f3c6f2f7f8f2f8f90fdbf1f5e2f','--plan-gate-json',str(p),'--plan-gate-json-sha256','a1fce4363854ff888cff4b8e7875d600c268239041f7af2bbfc4618cbafe0f8d','--operator','vahid','--reason','ok','--operator-confirmed','--i-understand-post-apply-evidence-only','--i-understand-no-additional-firewall-apply','--i-understand-no-production-traffic-acceptance','--i-understand-no-miner-traffic-acceptance','--i-confirm-runtime-path-evidence-required-next','--i-confirm-stratum-transcript-required-next','--i-confirm-visibility-bundle-required-next','--i-confirm-abuse-1h-required-before-customer-traffic','--i-confirm-restart-container-order-required-before-limited-acceptance','--output','human','--config','configs/mpf.example.yaml']); assert r.exit_code==0
