from __future__ import annotations
import json
from pathlib import Path
from types import SimpleNamespace
import pytest
from typer.testing import CliRunner
from mpf import __version__
from mpf.config import load_config
from mpf.interfaces.cli import app
from mpf.services import customer_read_service
from mpf.services.phase11_single_customer_firewall_apply_gate_service import build_phase11_single_customer_firewall_apply_gate_report

def _cfg(): return load_config(Path('configs/mpf.example.yaml'))
def _rows(*rows): return customer_read_service.CustomerList(ok=True,message='ok',customers=list(rows))
def _staged(status='paused', lane='btc', port=20101): return SimpleNamespace(id=1,customer_key='limited-btc-001',lane=lane,port=port,status=status)
def _live(ok=True):
    if ok: return '*nat\n:MPF_NAT_PRE - [0:0]\n-A MPF_NAT_PRE -p tcp --dport 20001 -j DNAT --to-destination 172.18.0.3:60010\n*filter\n:MPFC_20001 - [0:0]\n'
    return '*filter\n:INPUT ACCEPT [0:0]\n'
def _gate(**u):
    d={"component":"phase11_single_customer_firewall_plan_gate","expected_version":"0.1.202","repository_version":"0.1.202","candidate_customer_key":"limited-btc-001","candidate_lane":"btc","candidate_public_port":20101,"candidate_backend_target":"172.18.0.3:60010","phase11e_firewall_plan_gate_ready":True,"firewall_plan_generated":True,"firewall_apply_allowed":False,"nat_apply_allowed":False,"iptables_restore_authorized":False,"production_traffic_enabled":False,"miner_traffic_allowed":False,"phase11_accepted":False,"limited_onboarding_allowed":False,"db_mutation_performed":False,"firewall_mutation_performed":False,"nat_mutation_performed":False,"conntrack_mutation_performed":False,"docker_mutation_performed":False,"mutation_performed":False,"firewall_plan_summary":{"intended_chain":"MPFC_20101","intended_nat_chain":"MPF_NAT_PRE","intended_public_port":20101,"intended_backend_target":"172.18.0.3:60010","intended_customer_key":"limited-btc-001","intended_lane":"btc","safety":{"iptables_restore_authorized":False,"apply_command_approved":False,"mutation_performed":False,"existing_canary_20001_artifact_modified":False,"production_traffic_enabled":False}},"blockers":[],"warnings":[],"next_required_step":"phase11e_firewall_apply_gate_pr","final_decision":"PHASE11_SINGLE_CUSTOMER_FIREWALL_PLAN_GATE_READY"}
    d.update(u); return d
def _w(tmp,d,name='g.json'): p=tmp/name; p.write_text(json.dumps(d)); return p
def _snap(tmp,txt,name='iptables.txt'): p=tmp/name; p.write_text(txt); return p
def _kw(tmp,**u):
    d=dict(expected_version=__version__,farm5_baseline_version='0.1.168',firewall_plan_gate_json=_w(tmp,_gate()),candidate_customer_key='limited-btc-001',candidate_lane='btc',candidate_public_port=20101,candidate_backend_target='172.18.0.3:60010',operator='vahid',reason='ok',operator_confirmed=True,i_understand_apply_gate_only=True,i_understand_no_firewall_apply_in_this_pr=True,i_understand_no_nat_apply_in_this_pr=True,i_understand_no_iptables_restore_in_this_pr=True,i_understand_no_production_traffic=True,i_understand_no_miner_traffic_yet=True,i_confirm_limited_single_customer_scope=True,i_confirm_restore_point_required_before_apply=True,i_confirm_operator_lock_required_before_apply=True,i_confirm_rollback_artifact_required_before_apply=True,i_confirm_pre_apply_snapshot_required_before_apply=True,i_confirm_post_apply_verification_required=True,i_confirm_runtime_path_evidence_required_after_apply=True,i_confirm_abuse_1h_evidence_required_before_customer_traffic=True,i_confirm_restart_container_order_evidence_required_before_customer_traffic=True,live_snapshot_file=_snap(tmp,_live()),collect_live=False)
    d.update(u); return d

def _run(tmp,monkeypatch,**u): monkeypatch.setattr(customer_read_service,'list_customer_status',lambda *a,**k:_rows(_staged())); return build_phase11_single_customer_firewall_apply_gate_report(_cfg(),**_kw(tmp,**u))

def test_apply_gate_ready_from_valid_plan_gate_json_db_customer_and_file_backed_live_firewall(tmp_path,monkeypatch): assert _run(tmp_path,monkeypatch)['final_decision']=='PHASE11_SINGLE_CUSTOMER_FIREWALL_APPLY_GATE_READY'

def test_blocks_missing_firewall_plan_gate_json(tmp_path,monkeypatch): r=_run(tmp_path,monkeypatch,firewall_plan_gate_json=tmp_path/'x'); assert 'firewall_plan_gate_json_missing' in r['blockers']
def test_blocks_invalid_firewall_plan_gate_json(tmp_path,monkeypatch): p=tmp_path/'x.json'; p.write_text('{'); r=_run(tmp_path,monkeypatch,firewall_plan_gate_json=p); assert 'firewall_plan_gate_json_invalid' in r['blockers']
def test_blocks_firewall_plan_gate_not_ready(tmp_path,monkeypatch): r=_run(tmp_path,monkeypatch,firewall_plan_gate_json=_w(tmp_path,_gate(final_decision='X'),'x.json')); assert 'firewall_plan_gate_not_ready' in r['blockers']
def test_blocks_firewall_plan_gate_safety_boundary_open(tmp_path,monkeypatch): r=_run(tmp_path,monkeypatch,firewall_plan_gate_json=_w(tmp_path,_gate(firewall_apply_allowed=True),'x.json')); assert 'firewall_plan_gate_safety_boundary_open' in r['blockers']
def test_blocks_firewall_plan_gate_mutation_detected(tmp_path,monkeypatch): r=_run(tmp_path,monkeypatch,firewall_plan_gate_json=_w(tmp_path,_gate(mutation_performed=True),'x.json')); assert 'firewall_plan_gate_mutation_detected' in r['blockers']
def test_blocks_missing_firewall_plan_summary(tmp_path,monkeypatch): r=_run(tmp_path,monkeypatch,firewall_plan_gate_json=_w(tmp_path,_gate(firewall_plan_summary=None),'x.json')); assert 'firewall_plan_summary_missing' in r['blockers']
def test_blocks_plan_summary_scope_mismatch(tmp_path,monkeypatch): g=_gate(); g['firewall_plan_summary']['intended_chain']='x'; r=_run(tmp_path,monkeypatch,firewall_plan_gate_json=_w(tmp_path,g,'x.json')); assert 'firewall_plan_summary_scope_mismatch' in r['blockers']

@pytest.mark.parametrize('key,val,blk',[('expected_version','0','expected_version_mismatch'),('farm5_baseline_version','0','farm5_baseline_version_mismatch'),('candidate_customer_key','x','candidate_customer_key_invalid'),('candidate_lane','zec','candidate_lane_invalid'),('candidate_public_port',1,'candidate_public_port_invalid'),('candidate_backend_target','x','candidate_backend_target_invalid'),('operator_confirmed',False,'operator_not_confirmed'),('i_understand_apply_gate_only',False,'apply_gate_only_boundary_not_confirmed'),('i_understand_no_firewall_apply_in_this_pr',False,'no_firewall_apply_boundary_not_confirmed'),('i_understand_no_nat_apply_in_this_pr',False,'no_nat_apply_boundary_not_confirmed'),('i_understand_no_iptables_restore_in_this_pr',False,'no_iptables_restore_boundary_not_confirmed'),('i_understand_no_production_traffic',False,'no_production_traffic_boundary_not_confirmed'),('i_understand_no_miner_traffic_yet',False,'no_miner_traffic_boundary_not_confirmed'),('i_confirm_limited_single_customer_scope',False,'limited_single_customer_scope_not_confirmed'),('i_confirm_restore_point_required_before_apply',False,'restore_point_requirement_not_confirmed'),('i_confirm_operator_lock_required_before_apply',False,'operator_lock_requirement_not_confirmed'),('i_confirm_rollback_artifact_required_before_apply',False,'rollback_artifact_requirement_not_confirmed'),('i_confirm_pre_apply_snapshot_required_before_apply',False,'pre_apply_snapshot_requirement_not_confirmed'),('i_confirm_post_apply_verification_required',False,'post_apply_verification_requirement_not_confirmed'),('i_confirm_runtime_path_evidence_required_after_apply',False,'runtime_path_evidence_requirement_not_confirmed'),('i_confirm_abuse_1h_evidence_required_before_customer_traffic',False,'abuse_1h_requirement_not_confirmed'),('i_confirm_restart_container_order_evidence_required_before_customer_traffic',False,'restart_container_order_requirement_not_confirmed')])
def test_confirmations_and_inputs(tmp_path,monkeypatch,key,val,blk): assert blk in _run(tmp_path,monkeypatch,**{key:val})['blockers']

def test_blocks_db_read_failure(tmp_path,monkeypatch): monkeypatch.setattr(customer_read_service,'list_customer_status',lambda *a,**k: customer_read_service.CustomerList(ok=False,message='x',customers=[])); assert 'db_read_failed' in build_phase11_single_customer_firewall_apply_gate_report(_cfg(),**_kw(tmp_path))['blockers']
def test_blocks_missing_staged_customer(tmp_path,monkeypatch): monkeypatch.setattr(customer_read_service,'list_customer_status',lambda *a,**k:_rows()); assert 'staged_customer_missing' in build_phase11_single_customer_firewall_apply_gate_report(_cfg(),**_kw(tmp_path))['blockers']
def test_blocks_duplicate_staged_customer(tmp_path,monkeypatch): monkeypatch.setattr(customer_read_service,'list_customer_status',lambda *a,**k:_rows(_staged(),_staged())); assert 'staged_customer_duplicate' in build_phase11_single_customer_firewall_apply_gate_report(_cfg(),**_kw(tmp_path))['blockers']
def test_blocks_staged_customer_wrong_lane(tmp_path,monkeypatch): monkeypatch.setattr(customer_read_service,'list_customer_status',lambda *a,**k:_rows(_staged(lane='zec'))); assert 'staged_customer_scope_mismatch' in build_phase11_single_customer_firewall_apply_gate_report(_cfg(),**_kw(tmp_path))['blockers']
def test_blocks_staged_customer_wrong_port(tmp_path,monkeypatch): monkeypatch.setattr(customer_read_service,'list_customer_status',lambda *a,**k:_rows(_staged(port=1))); assert 'staged_customer_scope_mismatch' in build_phase11_single_customer_firewall_apply_gate_report(_cfg(),**_kw(tmp_path))['blockers']
def test_blocks_staged_customer_active_status(tmp_path,monkeypatch): monkeypatch.setattr(customer_read_service,'list_customer_status',lambda *a,**k:_rows(_staged(status='active'))); assert 'staged_customer_not_paused' in build_phase11_single_customer_firewall_apply_gate_report(_cfg(),**_kw(tmp_path))['blockers']
def test_blocks_candidate_port_collision(tmp_path,monkeypatch): monkeypatch.setattr(customer_read_service,'list_customer_status',lambda *a,**k:_rows(_staged(),SimpleNamespace(id=2,customer_key='x',lane='btc',port=20101,status='paused'))); assert 'candidate_port_collision' in build_phase11_single_customer_firewall_apply_gate_report(_cfg(),**_kw(tmp_path))['blockers']
def test_blocks_live_firewall_snapshot_missing(tmp_path,monkeypatch): assert 'live_firewall_snapshot_missing' in _run(tmp_path,monkeypatch,live_snapshot_file=None,collect_live=False)['blockers']
def test_blocks_live_firewall_read_failure(tmp_path,monkeypatch): assert 'live_firewall_read_failed' in _run(tmp_path,monkeypatch,live_snapshot_file=tmp_path/'none.txt')['blockers']
def test_blocks_if_live_20101_rule_already_exists(tmp_path,monkeypatch): assert 'live_20101_rule_already_exists' in _run(tmp_path,monkeypatch,live_snapshot_file=_snap(tmp_path,_live()+"-A MPF_NAT_PRE -p tcp --dport 20101 -j DNAT --to-destination 172.18.0.3:60010\n",'x1.txt'))['blockers']
def test_blocks_if_live_canary_20001_artifact_missing(tmp_path,monkeypatch): assert 'live_canary_20001_artifact_missing_or_ambiguous' in _run(tmp_path,monkeypatch,live_snapshot_file=_snap(tmp_path,'*filter\n','x2.txt'))['blockers']
def test_blocks_if_live_firewall_has_limited_customer_reference(tmp_path,monkeypatch): assert 'live_firewall_unexpected_limited_customer_reference' in _run(tmp_path,monkeypatch,live_snapshot_file=_snap(tmp_path,_live()+"# limited-btc-001\n",'x3.txt'))['blockers']
def test_output_never_authorizes_iptables_restore(tmp_path,monkeypatch): assert _run(tmp_path,monkeypatch)['iptables_restore_authorized'] is False
def test_output_never_allows_firewall_or_nat_apply(tmp_path,monkeypatch): r=_run(tmp_path,monkeypatch); assert r['firewall_apply_allowed'] is False and r['nat_apply_allowed'] is False
def test_output_never_allows_production_or_miner_traffic(tmp_path,monkeypatch): r=_run(tmp_path,monkeypatch); assert r['production_traffic_enabled'] is False and r['miner_traffic_allowed'] is False
def test_output_never_mutates_anything(tmp_path,monkeypatch): r=_run(tmp_path,monkeypatch); assert all(r[k] is False for k in ('db_mutation_performed','firewall_mutation_performed','nat_mutation_performed','conntrack_mutation_performed','docker_mutation_performed','mutation_performed'))
def test_output_contains_plan_gate_and_plan_summary_hashes(tmp_path,monkeypatch): r=_run(tmp_path,monkeypatch); assert r['firewall_plan_gate_json_sha256'] and r['plan_summary_sha256']

def test_cli_single_customer_firewall_apply_gate_json_smoke(tmp_path,monkeypatch):
    monkeypatch.setattr(customer_read_service,'list_customer_status',lambda *a,**k:_rows(_staged()))
    p=_w(tmp_path,_gate()); s=_snap(tmp_path,_live())
    r=CliRunner().invoke(app,['production','single-customer-firewall-apply-gate','--firewall-plan-gate-json',str(p),'--operator','vahid','--reason','ok','--operator-confirmed','--i-understand-apply-gate-only','--i-understand-no-firewall-apply-in-this-pr','--i-understand-no-nat-apply-in-this-pr','--i-understand-no-iptables-restore-in-this-pr','--i-understand-no-production-traffic','--i-understand-no-miner-traffic-yet','--i-confirm-limited-single-customer-scope','--i-confirm-restore-point-required-before-apply','--i-confirm-operator-lock-required-before-apply','--i-confirm-rollback-artifact-required-before-apply','--i-confirm-pre-apply-snapshot-required-before-apply','--i-confirm-post-apply-verification-required','--i-confirm-runtime-path-evidence-required-after-apply','--i-confirm-abuse-1h-evidence-required-before-customer-traffic','--i-confirm-restart-container-order-evidence-required-before-customer-traffic','--live-snapshot-file',str(s),'--output','json','--config','configs/mpf.example.yaml']); assert r.exit_code==0

def test_cli_single_customer_firewall_apply_gate_human_smoke(tmp_path,monkeypatch):
    monkeypatch.setattr(customer_read_service,'list_customer_status',lambda *a,**k:_rows(_staged()))
    p=_w(tmp_path,_gate(),'p2.json'); s=_snap(tmp_path,_live())
    r=CliRunner().invoke(app,['production','single-customer-firewall-apply-gate','--firewall-plan-gate-json',str(p),'--operator','vahid','--reason','ok','--operator-confirmed','--i-understand-apply-gate-only','--i-understand-no-firewall-apply-in-this-pr','--i-understand-no-nat-apply-in-this-pr','--i-understand-no-iptables-restore-in-this-pr','--i-understand-no-production-traffic','--i-understand-no-miner-traffic-yet','--i-confirm-limited-single-customer-scope','--i-confirm-restore-point-required-before-apply','--i-confirm-operator-lock-required-before-apply','--i-confirm-rollback-artifact-required-before-apply','--i-confirm-pre-apply-snapshot-required-before-apply','--i-confirm-post-apply-verification-required','--i-confirm-runtime-path-evidence-required-after-apply','--i-confirm-abuse-1h-evidence-required-before-customer-traffic','--i-confirm-restart-container-order-evidence-required-before-customer-traffic','--live-snapshot-file',str(s),'--output','human','--config','configs/mpf.example.yaml']); assert r.exit_code==0
