from types import SimpleNamespace
from mpf.services import phase11e_limited_activation_rollback_execute_service as service
from tests.test_phase11e_limited_activation_execute_service import _j,_sha,_rows
from mpf import __version__
def _k(t):
 scope={'candidate_customer_key':'limited-btc-001','lane':'btc','public_port':20101,'backend_target':'172.18.0.3:60010'};e=_j(t/'e.json',{'final_decision':'PHASE11E_LIMITED_ACTIVATION_EXECUTED_PENDING_EVIDENCE',**scope});r=_j(t/'r.json',{'component':'phase11e_limited_activation_rollback_package','final_decision':'PHASE11E_LIMITED_ACTIVATION_ROLLBACK_PACKAGE_READY','rollback_customer_key':'limited-btc-001','rollback_lane':'btc','rollback_public_port':20101,'rollback_backend_target':'172.18.0.3:60010'});a=_j(t/'a.json',{'final_decision':'PASS_NO_CUSTOMER_ARTIFACTS','unknown_mpf_artifacts':[],'forbidden_public_runtime_exposure':False,'production_gates_remain_closed':True});k={'expected_version':__version__,'activation_execution_json':str(e),'activation_execution_json_sha256':_sha(e),'limited_activation_rollback_package_json':str(r),'limited_activation_rollback_package_json_sha256':_sha(r),'artifact_gate_json':str(a),'artifact_gate_json_sha256':_sha(a),'operator':'op','reason':'r'};k.update({x:True for x in service.CONFIRMATIONS});return k
def test_rollback_exact_scope_only(monkeypatch,tmp_path):
 monkeypatch.setattr(service.customer_read_service,'list_customer_status',lambda *a,**k:_rows('active'));called=[];monkeypatch.setattr(service.customer_mutation_service,'rollback_phase11e_limited_customer',lambda *a,**k:(called.append(k) or SimpleNamespace(ok=True,message='OK')));r=service.build_phase11e_limited_activation_rollback_execute_report(SimpleNamespace(),**_k(tmp_path));assert r['final_decision']=='PHASE11E_LIMITED_ACTIVATION_ROLLBACK_EXECUTED_PENDING_EVIDENCE';assert r['changed_customers']==['limited-btc-001'];assert called[0]['customer_key']=='limited-btc-001'
def test_rollback_blocks_missing_confirmation_hash_and_paused(monkeypatch,tmp_path):
 monkeypatch.setattr(service.customer_read_service,'list_customer_status',lambda *a,**k:_rows('paused'));k=_k(tmp_path);k['operator_confirmed']=False;k['activation_execution_json_sha256']='bad';r=service.build_phase11e_limited_activation_rollback_execute_report(SimpleNamespace(),**k);assert r['final_decision']=='BLOCKED';assert r['mutation_performed'] is False
