from __future__ import annotations
import json
from pathlib import Path
from types import SimpleNamespace

from typer.testing import CliRunner

from mpf import __version__
from mpf.config import load_config
from mpf.interfaces.cli import app
from mpf.services import customer_read_service
from mpf.services.phase11_single_customer_firewall_plan_gate_service import build_phase11_single_customer_firewall_plan_gate_report

def _cfg(): return load_config(Path('configs/mpf.example.yaml'))
def _stage(**kw):
    d={"component":"phase11_single_customer_staging","expected_version":"0.1.200","repository_version":"0.1.200","mode":"execute-db-only","candidate_customer_key":"limited-btc-001","candidate_lane":"btc","candidate_public_port":20101,"candidate_backend_target":"172.18.0.3:60010","phase11e_single_customer_staging_ready":True,"phase11e_db_staging_allowed":True,"customer_created":True,"db_mutation_performed":True,"firewall_mutation_performed":False,"nat_mutation_performed":False,"conntrack_mutation_performed":False,"docker_mutation_performed":False,"phase11_accepted":False,"limited_onboarding_allowed":False,"production_traffic_enabled":False,"no_onboarding_authorized":True,"blockers":[],"warnings":[],"next_required_step":"phase11e_firewall_plan_gate_pr","final_decision":"PHASE11_SINGLE_CUSTOMER_DB_STAGING_EXECUTED"}
    d.update(kw);return d
def _w(tmp,d): p=tmp/'s.json'; p.write_text(json.dumps(d)); return p
def _kw(p):
    return dict(expected_version=__version__,farm5_baseline_version='0.1.168',staging_execute_json=p,candidate_customer_key='limited-btc-001',candidate_lane='btc',candidate_public_port=20101,candidate_backend_target='172.18.0.3:60010',operator='vahid',reason='ok',operator_confirmed=True,i_understand_plan_only=True,i_understand_no_firewall_apply=True,i_understand_no_nat_apply=True,i_understand_no_production_traffic=True,i_understand_no_miner_traffic_yet=True,i_confirm_restore_point_required_before_apply=True,i_confirm_lock_required_before_apply=True,i_confirm_rollback_plan_required_before_apply=True,i_confirm_restart_test_required_before_traffic=True,i_confirm_abuse_1h_required_before_traffic=True)
def _rows(*rows): return customer_read_service.CustomerList(ok=True,message='ok',customers=list(rows))
def _staged(status='paused', lane='btc', port=20101): return SimpleNamespace(id=1,customer_key='limited-btc-001',lane=lane,port=port,status=status)

def test_firewall_plan_gate_ready_from_valid_staging_execute_json_and_db_customer(tmp_path,monkeypatch): monkeypatch.setattr(customer_read_service,'list_customer_status',lambda *a,**k:_rows(_staged())); assert build_phase11_single_customer_firewall_plan_gate_report(_cfg(),**_kw(_w(tmp_path,_stage())))['final_decision']=='PHASE11_SINGLE_CUSTOMER_FIREWALL_PLAN_GATE_READY'
def test_blocks_missing_staging_execute_json(tmp_path): assert 'staging_execute_json_missing' in build_phase11_single_customer_firewall_plan_gate_report(_cfg(),**_kw(tmp_path/'x'))['blockers']
def test_blocks_invalid_staging_execute_json(tmp_path): p=tmp_path/'x.json'; p.write_text('{'); assert 'staging_execute_json_invalid' in build_phase11_single_customer_firewall_plan_gate_report(_cfg(),**_kw(p))['blockers']
def test_blocks_staging_execute_not_executed(tmp_path,monkeypatch): monkeypatch.setattr(customer_read_service,'list_customer_status',lambda *a,**k:_rows(_staged())); assert 'staging_execute_not_executed' in build_phase11_single_customer_firewall_plan_gate_report(_cfg(),**_kw(_w(tmp_path,_stage(final_decision='X'))))['blockers']
def test_blocks_staging_safety_boundary_open(tmp_path,monkeypatch): monkeypatch.setattr(customer_read_service,'list_customer_status',lambda *a,**k:_rows(_staged())); assert 'staging_safety_boundary_open' in build_phase11_single_customer_firewall_plan_gate_report(_cfg(),**_kw(_w(tmp_path,_stage(production_traffic_enabled=True))))['blockers']
def test_blocks_staging_firewall_mutation_true(tmp_path,monkeypatch): monkeypatch.setattr(customer_read_service,'list_customer_status',lambda *a,**k:_rows(_staged())); assert 'staging_firewall_or_nat_mutation_detected' in build_phase11_single_customer_firewall_plan_gate_report(_cfg(),**_kw(_w(tmp_path,_stage(firewall_mutation_performed=True))))['blockers']
def test_blocks_staging_nat_mutation_true(tmp_path,monkeypatch): monkeypatch.setattr(customer_read_service,'list_customer_status',lambda *a,**k:_rows(_staged())); assert 'staging_firewall_or_nat_mutation_detected' in build_phase11_single_customer_firewall_plan_gate_report(_cfg(),**_kw(_w(tmp_path,_stage(nat_mutation_performed=True))))['blockers']
def test_blocks_expected_version_mismatch(tmp_path): kw=_kw(_w(tmp_path,_stage())); kw['expected_version']='0'; assert 'expected_version_mismatch' in build_phase11_single_customer_firewall_plan_gate_report(_cfg(),**kw)['blockers']
def test_blocks_farm5_baseline_version_mismatch(tmp_path): kw=_kw(_w(tmp_path,_stage())); kw['farm5_baseline_version']='0'; assert 'farm5_baseline_version_mismatch' in build_phase11_single_customer_firewall_plan_gate_report(_cfg(),**kw)['blockers']
def test_blocks_wrong_candidate_key(tmp_path): kw=_kw(_w(tmp_path,_stage())); kw['candidate_customer_key']='x'; assert 'candidate_customer_key_invalid' in build_phase11_single_customer_firewall_plan_gate_report(_cfg(),**kw)['blockers']
def test_blocks_wrong_lane(tmp_path): kw=_kw(_w(tmp_path,_stage())); kw['candidate_lane']='zec'; assert 'candidate_lane_invalid' in build_phase11_single_customer_firewall_plan_gate_report(_cfg(),**kw)['blockers']
def test_blocks_wrong_port(tmp_path): kw=_kw(_w(tmp_path,_stage())); kw['candidate_public_port']=20000; assert 'candidate_public_port_invalid' in build_phase11_single_customer_firewall_plan_gate_report(_cfg(),**kw)['blockers']
def test_blocks_wrong_backend_target(tmp_path): kw=_kw(_w(tmp_path,_stage())); kw['candidate_backend_target']='x'; assert 'candidate_backend_target_invalid' in build_phase11_single_customer_firewall_plan_gate_report(_cfg(),**kw)['blockers']
def test_blocks_without_operator_confirmation(tmp_path): kw=_kw(_w(tmp_path,_stage())); kw['operator_confirmed']=False; assert 'operator_not_confirmed' in build_phase11_single_customer_firewall_plan_gate_report(_cfg(),**kw)['blockers']
def test_blocks_without_plan_only_confirmation(tmp_path): kw=_kw(_w(tmp_path,_stage())); kw['i_understand_plan_only']=False; assert 'plan_only_boundary_not_confirmed' in build_phase11_single_customer_firewall_plan_gate_report(_cfg(),**kw)['blockers']
def test_blocks_without_no_firewall_apply_confirmation(tmp_path): kw=_kw(_w(tmp_path,_stage())); kw['i_understand_no_firewall_apply']=False; assert 'no_firewall_apply_boundary_not_confirmed' in build_phase11_single_customer_firewall_plan_gate_report(_cfg(),**kw)['blockers']
def test_blocks_without_no_nat_apply_confirmation(tmp_path): kw=_kw(_w(tmp_path,_stage())); kw['i_understand_no_nat_apply']=False; assert 'no_nat_apply_boundary_not_confirmed' in build_phase11_single_customer_firewall_plan_gate_report(_cfg(),**kw)['blockers']
def test_blocks_without_no_production_confirmation(tmp_path): kw=_kw(_w(tmp_path,_stage())); kw['i_understand_no_production_traffic']=False; assert 'no_production_traffic_boundary_not_confirmed' in build_phase11_single_customer_firewall_plan_gate_report(_cfg(),**kw)['blockers']
def test_blocks_without_no_miner_traffic_confirmation(tmp_path): kw=_kw(_w(tmp_path,_stage())); kw['i_understand_no_miner_traffic_yet']=False; assert 'no_miner_traffic_boundary_not_confirmed' in build_phase11_single_customer_firewall_plan_gate_report(_cfg(),**kw)['blockers']
def test_blocks_without_restore_point_confirmation(tmp_path): kw=_kw(_w(tmp_path,_stage())); kw['i_confirm_restore_point_required_before_apply']=False; assert 'restore_point_requirement_not_confirmed' in build_phase11_single_customer_firewall_plan_gate_report(_cfg(),**kw)['blockers']
def test_blocks_without_lock_confirmation(tmp_path): kw=_kw(_w(tmp_path,_stage())); kw['i_confirm_lock_required_before_apply']=False; assert 'lock_requirement_not_confirmed' in build_phase11_single_customer_firewall_plan_gate_report(_cfg(),**kw)['blockers']
def test_blocks_without_rollback_confirmation(tmp_path): kw=_kw(_w(tmp_path,_stage())); kw['i_confirm_rollback_plan_required_before_apply']=False; assert 'rollback_plan_requirement_not_confirmed' in build_phase11_single_customer_firewall_plan_gate_report(_cfg(),**kw)['blockers']
def test_blocks_without_restart_confirmation(tmp_path): kw=_kw(_w(tmp_path,_stage())); kw['i_confirm_restart_test_required_before_traffic']=False; assert 'restart_test_requirement_not_confirmed' in build_phase11_single_customer_firewall_plan_gate_report(_cfg(),**kw)['blockers']
def test_blocks_without_abuse_1h_confirmation(tmp_path): kw=_kw(_w(tmp_path,_stage())); kw['i_confirm_abuse_1h_required_before_traffic']=False; assert 'abuse_1h_requirement_not_confirmed' in build_phase11_single_customer_firewall_plan_gate_report(_cfg(),**kw)['blockers']
def test_blocks_db_read_failure(tmp_path,monkeypatch): monkeypatch.setattr(customer_read_service,'list_customer_status',lambda *a,**k: customer_read_service.CustomerList(ok=False,message='x',customers=[])); assert 'db_read_failed' in build_phase11_single_customer_firewall_plan_gate_report(_cfg(),**_kw(_w(tmp_path,_stage())))['blockers']
def test_blocks_missing_staged_customer(tmp_path,monkeypatch): monkeypatch.setattr(customer_read_service,'list_customer_status',lambda *a,**k:_rows()); assert 'staged_customer_missing' in build_phase11_single_customer_firewall_plan_gate_report(_cfg(),**_kw(_w(tmp_path,_stage())))['blockers']
def test_blocks_duplicate_staged_customer(tmp_path,monkeypatch): monkeypatch.setattr(customer_read_service,'list_customer_status',lambda *a,**k:_rows(_staged(),_staged())); assert 'staged_customer_duplicate' in build_phase11_single_customer_firewall_plan_gate_report(_cfg(),**_kw(_w(tmp_path,_stage())))['blockers']
def test_blocks_staged_customer_wrong_lane(tmp_path,monkeypatch): monkeypatch.setattr(customer_read_service,'list_customer_status',lambda *a,**k:_rows(_staged(lane='zec'))); assert 'staged_customer_scope_mismatch' in build_phase11_single_customer_firewall_plan_gate_report(_cfg(),**_kw(_w(tmp_path,_stage())))['blockers']
def test_blocks_staged_customer_wrong_port(tmp_path,monkeypatch): monkeypatch.setattr(customer_read_service,'list_customer_status',lambda *a,**k:_rows(_staged(port=1))); assert 'staged_customer_scope_mismatch' in build_phase11_single_customer_firewall_plan_gate_report(_cfg(),**_kw(_w(tmp_path,_stage())))['blockers']
def test_blocks_staged_customer_not_safe_status(tmp_path,monkeypatch): monkeypatch.setattr(customer_read_service,'list_customer_status',lambda *a,**k:_rows(_staged(status='deleted'))); assert 'staged_customer_not_safe_status' in build_phase11_single_customer_firewall_plan_gate_report(_cfg(),**_kw(_w(tmp_path,_stage())))['blockers']
def test_blocks_candidate_port_collision(tmp_path,monkeypatch): monkeypatch.setattr(customer_read_service,'list_customer_status',lambda *a,**k:_rows(_staged(),SimpleNamespace(id=2,customer_key='x',lane='btc',port=20101,status='paused'))); assert 'candidate_port_collision' in build_phase11_single_customer_firewall_plan_gate_report(_cfg(),**_kw(_w(tmp_path,_stage())))['blockers']
def test_output_never_authorizes_iptables_restore(tmp_path,monkeypatch): monkeypatch.setattr(customer_read_service,'list_customer_status',lambda *a,**k:_rows(_staged())); assert build_phase11_single_customer_firewall_plan_gate_report(_cfg(),**_kw(_w(tmp_path,_stage())))['iptables_restore_authorized'] is False
def test_output_never_allows_firewall_or_nat_apply(tmp_path,monkeypatch): monkeypatch.setattr(customer_read_service,'list_customer_status',lambda *a,**k:_rows(_staged())); r=build_phase11_single_customer_firewall_plan_gate_report(_cfg(),**_kw(_w(tmp_path,_stage()))); assert r['firewall_apply_allowed'] is False and r['nat_apply_allowed'] is False
def test_output_never_allows_production_or_miner_traffic(tmp_path,monkeypatch): monkeypatch.setattr(customer_read_service,'list_customer_status',lambda *a,**k:_rows(_staged())); r=build_phase11_single_customer_firewall_plan_gate_report(_cfg(),**_kw(_w(tmp_path,_stage()))); assert r['production_traffic_enabled'] is False and r['miner_traffic_allowed'] is False
def test_cli_single_customer_firewall_plan_gate_json_smoke(tmp_path,monkeypatch): monkeypatch.setattr(customer_read_service,'list_customer_status',lambda *a,**k:_rows(_staged())); p=_w(tmp_path,_stage()); r=CliRunner().invoke(app,['production','single-customer-firewall-plan-gate','--staging-execute-json',str(p),'--operator','vahid','--reason','ok','--operator-confirmed','--i-understand-plan-only','--i-understand-no-firewall-apply','--i-understand-no-nat-apply','--i-understand-no-production-traffic','--i-understand-no-miner-traffic-yet','--i-confirm-restore-point-required-before-apply','--i-confirm-lock-required-before-apply','--i-confirm-rollback-plan-required-before-apply','--i-confirm-restart-test-required-before-traffic','--i-confirm-abuse-1h-required-before-traffic','--output','json','--config','configs/mpf.example.yaml']); assert r.exit_code==0
def test_cli_single_customer_firewall_plan_gate_human_smoke(tmp_path,monkeypatch): monkeypatch.setattr(customer_read_service,'list_customer_status',lambda *a,**k:_rows(_staged())); p=_w(tmp_path,_stage()); r=CliRunner().invoke(app,['production','single-customer-firewall-plan-gate','--staging-execute-json',str(p),'--operator','vahid','--reason','ok','--operator-confirmed','--i-understand-plan-only','--i-understand-no-firewall-apply','--i-understand-no-nat-apply','--i-understand-no-production-traffic','--i-understand-no-miner-traffic-yet','--i-confirm-restore-point-required-before-apply','--i-confirm-lock-required-before-apply','--i-confirm-rollback-plan-required-before-apply','--i-confirm-restart-test-required-before-traffic','--i-confirm-abuse-1h-required-before-traffic','--output','human','--config','configs/mpf.example.yaml']); assert r.exit_code==0
